### ISSUE TITLE
Feature: catch MemoryError from subprocesses, return more helpful info to user

### ISSUE THREAD

**Issue by blake-riley** [ExcitedStates/qfit-3.0#130]
**To Reproduce**
1. Run qFit_protein, default parameters, with a big (~ >1000) residue protein, and some amount of parallelization (e.g. -p 20).
2. At some point, you'll run into MemoryError, which kills one (or multiple) subprocesses.

```
Process ForkServerPoolWorker-6:
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/qfit/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/user/miniconda3/envs/qfit/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/miniconda3/envs/qfit/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/home/user/miniconda3/envs/qfit/lib/python3.7/multiprocessing/queues.py", line 352, in get
    res = self._reader.recv_bytes()
  File "/home/user/miniconda3/envs/qfit/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/user/miniconda3/envs/qfit/lib/python3.7/multiprocessing/connection.py", line 411, in _recv_bytes
    return self._recv(size)
  File "/home/user/miniconda3/envs/qfit/lib/python3.7/multiprocessing/connection.py", line 386, in _recv
    buf.write(chunk)
MemoryError
```

**Software & OS Version:**
 - qFit version: v3.2.0-master
 - Python version: 3.7
 - OS: Ubuntu Linux 16.4

**Expected behavior**
It would be nice if multiprocessing.Pool caught MemoryError from PoolWorkers, and:
a) assessed the memory usage of the largest thread
b) auto relaunched (?) the pool with a dynamically-chosen smaller pool size so as not to crash,
c) returned a nice error message telling the user they ran into MemoryError, and they should decrease parallelization.

A good roadmap for this would be (c) then (b) then (a).

**Comment by blake-riley** [comment]
Also, probably should look into https://docs.python.org/3/library/multiprocessing.shared_memory.html to see if there are any RO objects that this would suit.

**Comment by blake-riley** [comment]
Note:
- Maybe poll `multiprocessing.Pool._pool` to catch crashed executors? This is hacky. Check [so:24396147](https://stackoverflow.com/questions/24396147/retrieve-exit-code-of-processes-launched-with-multiprocessing-pool-map/24396655#24396655) and [so:24894682](https://stackoverflow.com/questions/24894682/python-multiprocessing-crash-in-subprocess/24894997#24894997) for examples.
- [bpo9205](https://bugs.python.org/issue9205) fixed this in [`concurrent.futures.ProcessPoolExecutor`](https://docs.python.org/3.8/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor) (a higher-level interface), but not in `multiprocessing.Pool` (if this route is used, make sure to do a speed comparison).
    - [bpo22393](https://bugs.python.org/issue22393) is still not merged, the suggested workaround is to [use concurrent.futures instead](https://bugs.python.org/issue22393#msg315687)
    - [Nice examples](https://rednafi.github.io/digressions/python/2020/04/21/python-concurrent-futures.html) of how to use concurrent.futures
- Look into [billiard](https://billiard.readthedocs.io/en/latest/) for an alternative implementation of Pool (in which this is supposedly fixed?)

**Comment by stephaniewankowicz** [comment]
We have fixed how maps are handled in qFit protein and so this is complete.
