### ISSUE TITLE
Too many iterative rounds for 1n55 when doing phenix refinement

### ISSUE THREAD

**Issue by ss199514** [ExcitedStates/qfit-3.0#135]
**Describe the bug**
When the phenix refinement script is run on 1n55 multiconformer_model2.pdb, it's doing a ton of iterative rounds (I stopped at 1n55_002_240). 

**To Reproduce**
1. qfit_protein /path/to/1n55.mtz -l FWT,PHWT /path/to/1N55.pdb
2. qfit_final_refine_xray.sh multiconformer_model2.pdb /path/to/1n55.mtz

**Expected behavior**
The refinement script will keep running and producing models (Ran for 5 days when I killed the run)

**Additional context**
Does it have to do with the number of conformers it is finding for the specific protein? It's culling slower and one refined model is not too different from the successive refined model?

**Software & OS Version:**
 - qFit version: [e.g. v3.1.2-2d21d4d]
 - Python version: [e.g. 3.8.3]
 - OS: [Ubuntu Linux 20.04]

**Attach files:**
- `qfit.log` (debug mode)
    Attached the qfit_final_refine_xray.sh --debug log [file][1n55 qfit_final_refine_xray.log](https://github.com/ExcitedStates/qfit-3.0/files/5772415/1n55.qfit_final_refine_xray.log)

**Comment by blake-riley** [comment]
#169 put a hard limit on the number of loops in iterative refinement.
Not perfect, but this issue is closed.
