### ISSUE TITLE
qFit crashes with large proteins  due to memory error (when map -> multiprocessing). :bug:

### ISSUE THREAD

**Issue by stephaniewankowicz** [ExcitedStates/qfit-3.0#139]
**Describe the bug**

**To Reproduce**
1. I am unclear the minimum size needed but have observed this problem in proteins >1100 residues. 

This is happening when feeding into the qFit residue parallel script. Need to make a flag to route around this (at least tmp). 

**Expected behavior**

**Additional context**

**Software & OS Version:**
 - qFit version: newest master
 - Python version: 3.8 
 - OS: Linux

**Comment by blake-riley** [comment]
Can you paste here a traceback of what the error is?
Is it a MemoryError?
What do you mean by "when map -> multiprocessing"?
Does it run OK when you choose 1 process?
How much RAM on the machine you're running it on?

**Comment by stephaniewankowicz** [comment]
This is a duplicate issue
