### ISSUE TITLE
:bug:multiconformer_model.pdb not found error when it is actually present

### ISSUE THREAD

**Issue by ashrayar** [ExcitedStates/qfit-3.0#190]
**Describe the bug**
qfit_protein looks for multiconformer_model.pdb in the current directory and not in the directory passed through -d option (which is where the multiconformer_model.pdb file is)

**To Reproduce**
1. qfit_protein my_dir/my_map_file.ccp4 -l 2FOFCWT,PH2FOFCWT my_pdb.pdb -d my_dir -r 1.0
**Expected behavior**
qfit_protein reads multiconformer_model.pdb from my_dir directory and proceeds to build segments

**Additional context**
The input PDB file is in the current directory but the map file is in the directory passed through -d option

**Software & OS Version:**
 - qFit version: [e.g. v3.1.2-1c9eecd9]
 - Python version: [e.g. 3.8.1.3]
 - OS: [e.g. macOS 11.6.1
[qfit.log](https://github.com/ExcitedStates/qfit-3.0/files/8536307/qfit.log)
]

**Attach files:**
- `qfit.log` (debug mode)
    If you can, please run the same command again with a `--debug` flag. qFit will output a detailed `qfit.log` file. This log contains a lot of extra detail that will help project maintainers identify where in the program an issue occurred.
- Please attach structure/map files to help troubleshoot, if possible.

**Comment by blake-riley** [comment]
Yep, thanks. My fault from the changes I made in #185 .
