### ISSUE TITLE
indentation issue in qfit_protein.py

### ISSUE THREAD

**Issue by bmhudson** [ExcitedStates/qfit-3.0#23]
Indentation issue on lines 300-304 of this file:
https://github.com/ExcitedStates/qfit-3.0/blob/dev/qfit/qfit_protein.py

**Comment by vdbedem** [comment]
File looks fine to me, and code (v3.1.1) executes without issues. What version are you using?

**Comment by bmhudson** [comment]
We should be using the most up to date version as our guy mentioned he
noticed the dev - master merge. He fixed it on our end so it's running fine
here, but asked me to let you know. If you don't see a problem, then I
guess it's fine!

**Comment by vdbedem** [comment]
Thanks!
