### ISSUE TITLE
Add test cases with biological significance for improved qFit testing

### ISSUE THREAD

**Issue by ashrayar** [ExcitedStates/qfit-3.0#266]
Identify protein structures in PDB which can be used to test qFit. Within each structure, identify residues which have been confidently and correctly modeled with multiple conformers by the depositors. Use these residues to check if qFit is able to model them well. Some metrics to check if qFit worked:
- Number of altconfs
- Rotamer angles of side chains
- RMSD
- Fit to density (EDIA/RSCC)
Add these test cases to the example folder and eventually identify cases and metrics for continuous integration testing.

**Comment by stephaniewankowicz** [comment]
This is done but will not exist in this directory
