### ISSUE TITLE
residue with improper altloc message when running qfit_final_refine_xray.sh

### ISSUE THREAD

**Issue by dacase** [ExcitedStates/qfit-3.0#314]
I've seen this problem with many proteins, but here I'll just describe results using 2ol9, a very simple peptide structure with just 6 standard residues.

After running `phenix.composite_omit_map` and `qfit`, I did the following:
```
qfit_final_refine_xray.sh  2ol9.mtz
```

After several cycles of refinement, phenix stops with this message (before any real work has been done):
```
residue with improper altloc
  "ATOM    127  N   ASN A   5 .*.     N  "
  "ATOM    128  CA  ASN A   5 .*.     C  "
  "ATOM    129  C   ASN A   5 .*.     C  "
  "ATOM    130  O   ASN A   5 .*.     O  "
  "ATOM    131  HA  ASN A   5 .*.     H  "
  "ATOM    132  H   ASN A   5 .*.     H  "
  "ATOM    133  CB AASN A   5 .*.     C  "
  "ATOM    134  CG AASN A   5 .*.     C  "
  "ATOM    135  OD1AASN A   5 .*.     O  "
  "ATOM    136  ND2AASN A   5 .*.     N  "
  "ATOM    137  H  AASN A   5 .*.     H  "
  "ATOM    138  HB2AASN A   5 .*.     H  "
  "ATOM    139  HB3AASN A   5 .*.     H  "
  "ATOM    140 HD21AASN A   5 .*.     H  "
  "ATOM    141 HD22AASN A   5 .*.     H  "
  "ATOM    142  CB BASN A   5 .*.     C  "
  "ATOM    143  CG BASN A   5 .*.     C  "
  "ATOM    144  OD1BASN A   5 .*.     O  "
  "ATOM    145  ND2BASN A   5 .*.     N  "
  "ATOM    146  HB2BASN A   5 .*.     H  "
  "ATOM    147  HB3BASN A   5 .*.     H  "
  "ATOM    148 HD21BASN A   5 .*.     H  "
  "ATOM    149 HD22BASN A   5 .*.     H  "
```
The code then gets into a loop of repeated refinement steps that show the same problem.  There is never the final cleanup step (I think because the max iterations is exceeded).

`phenix` has a point here (I think): atom 132 is H with no altloc code, and atom 137 is H with altloc of "A".  The problem happens after three cycles: that is, in the `2ol9_003.pdb` file, both "H" atoms in residue 5 have altlocs (one is "A" and the other "B").  But in `2ol9_004.pdb`, the altloc "B" has been changed to a space, as indicated above.

I'm using `phenix-1.20.1-4487` as instructed.

Any clues about what is going on here, or any workaround?  FWIW, I get this error in most cases, including the 3k0n ID used in the examples in the README.  I've tried a Google search on the error message, but didn't find anything the seemed to help.

...thanks for a great program!....dave case

**Comment by stephaniewankowicz** [comment]
Hi Dave,

Thanks for your comments/response. We have updated our refinement strategy significantly and should be pushing to main soon. Please let us know if you are seeing any weird results so we can make the next push as stable as possible!

Thanks,
Stephanie
