### ISSUE TITLE
qfit_ligand assigns occupancies in only a specific range (0.2-0.35):bug:

### ISSUE THREAD

**Issue by ss199514** [ExcitedStates/qfit-3.0#315]
**Describe the bug**
qfit_ligand is consistently assigning occupancies in the range of 0.2-0.35 for >40 PDBs (5-6 different datasets). It assigned an occupancy of 0.2 for the majority of these datasets.

**To Reproduce**
Step 1--> Fetch files

Use get_structures.sh (phenix.fetch_pdb –mtz)

Step 2--> Running ready set

Original.pdb (from the PDB fetched ^^)

Step 3--> Generate composite omit map

phenix.composite_omit_map original.pdb phenix_fetch_sf.mtz ../ready_set/*.ligands.cif input.xray_data.labels=FOBS,SIGFOBS input.xray_data.r_free_flags.label=R-free-flags

Step 4--> Run qfit_ligand

qfit_ligand composite_omit_map.mtz -l 2FOFCWT,PH2FOFCWT original.pdb chain,number

**Expected behavior**
An inspection of the occupancies assigned by qfit_ligand will show that it's skewed towards ~0.2 

**Additional context**
Examples structures to test this on:
7ZWO,7ZWP,7ZWQ,7ZWR,7ZWS,7ZWT,7ZWU,7ZWV,7ZWW,7ZWX,7ZWY,7ZWZ

**Software & OS Version:**
 - qFit version: [v3.2.0 and 3.2.2]

**Attach files:**

[v3.2.0_multiconformer_A_201.txt](https://github.com/ExcitedStates/qfit-3.0/files/10924036/v3.2.0_multiconformer_A_201.txt)

**Comment by stephaniewankowicz** [comment]
@ss199514 did you re-test these PDBs and get higher occupancies? The deposited occupancies for many of these ligands are less than 1. Was the sum of occupancies closer to 0.5 or higher? Just trying to figure out if we should close this issue or not.

**Comment by stephaniewankowicz** [comment]
Re-worked with @jessicaflowers changes
