### ISSUE TITLE
The TUTORIAL link in README.md seems broken

### ISSUE THREAD

**Issue by dacase** [ExcitedStates/qfit-3.0#342]

**Comment by fraserlab** [comment]
Major updates coming soon Dave - so I'd suggest waiting a few days before getting too deep! Preprint on new features, etc coming by end of the month

**Comment by stephaniewankowicz** [comment]
Hi Dave,
Thank you for bringing this to our attention. The link should now be fixed! Let us know if having more details in the tutorials would be helpful.
