### ISSUE TITLE
Issues installing qFit on M1 Mac

### ISSUE THREAD

**Issue by stephaniewankowicz** [ExcitedStates/qfit-3.0#356]
I was having issues install qFit on my laptop.

To fix, I needed to:
1) update python to 3.9
2) update numpy to 1.22

Before making a PR, need to test if this configuration of packaging will work on linux.

**Comment by helenginn** [comment]
A couple of points here, I am using an M2 Mac:
- small point, would be lovely to have a short warning that installation details for M1 Macs are different _before_ the detailed installation instructions - saves a bit of time attempting to install everything, failing, diagnosing and only then scrolling down (as I did!).
- I also could not get this to work with Python 3.12, and needed to drop down to Python 3.10 to allow the numpy and mkl dependencies to work. I don't know about Python 3.11.

After this, it installed fine.
