### ISSUE TITLE
qfit_residue is missing

### ISSUE THREAD

**Issue by jasonkey** [ExcitedStates/qfit-3.0#404]
Hi, 

I noticed that `qfit_residue --help` fails with this error 

```
Traceback (most recent call last):
  File "/programs/x86_64-linux/qfit/2024.2/bin/qfit_residue", line 5, in <module>
    from qfit.qfit_residue import main
ModuleNotFoundError: No module named 'qfit.qfit_residue'
```

I also don't see a qfit_residue.py in the repo or in site-packages/qfit 

This is using the 2024.2 release.

**Comment by stephaniewankowicz** [comment]
Hi Jason,

Thank you for pointing that out. qFit residue was removed (you can run it via qFit protein) but we did not update the example page! 

This is now updated in main.
