### ISSUE TITLE
Issue with generating `multiconformer_model2.pdb` with example 3K0N

### ISSUE THREAD

**Issue by sai-advaith** [ExcitedStates/qfit-3.0#435]
Hi,

I setup the github repository in my location machine (Ubuntu 22) by cloning the repository and following the instructions in the README file.

After which, I rand the code with the example files provided (`qfit_protein example/qfit_protein_example/3k0n_map.mtz -l 2FOFCWT,PH2FOFCWT example/qfit_protein_example/3k0n_refine.pdb`).

The code generated each residue in a separate directory `A_i`. However, at `A_7`, the code gives a warning `[A/PHE7] Too many conformers generated (17100). Splitting QP scoring` and the tqdm bar does not progress from there. Similar problems happen with multiple cycles.

Is there a reason why the code does not work with the examples provided on my end?

Please let me know if you need any additional details.

**Comment by stephaniewankowicz** [comment]
Hi @sai-advaith, 

We apologize. There is an error with oversampling aromatic residues in the main branch.  We are hoping to update the main this week, but I would suggest using the dev branch in the meantime, as that error is fixed there.

**Comment by sai-advaith** [comment]
I see. Has the error been fixed in the main branch?

Also, I am currently working with the dev branch and it works fine. So, thanks for the suggestion!

I wanted to run the code with my own data. In the [paper](https://dx.doi.org/10.1002/pro.4001), your team mentioned that the input density files are converted to an absolute scale, i.e., to electrons per Angstroms cube units. 

In my experiment, I am using a 2fofc ccp4 file along with the protein structure from rcsb (with resolution provided). Where in the codbase is the density grid of 2fofc file converted to an absolute scale? I noticed that this only happens in [FFTransformer](https://github.com/ExcitedStates/qfit-3.0/blob/251b2e2ebe4a9fd6f69f75926cf14f99c57df26b/src/qfit/transformer.py#L68), which is used for MTZ inputs. Could you please let me know where the conversion to absolute scale take place for ccp4 inputs.

Thanks!

**Comment by sai-advaith** [comment]
Hi,

Thank you for your reply.

I tried setting up both, dev and main branch on my local machine a few days ago. After that, I tried to generate 5 alternate conformers in residue 113 of 3K0N's chain A using the command from [README](https://github.com/ExcitedStates/qfit-3.0/blob/main/example/README.md): `qfit_protein qfit_protein_example/3k0n_map.mtz -l 2FOFCWT,PH2FOFCWT qfit_protein_example/3k0n_refine.pdb --residue A,113`

I get similar outputs from both branches: `[A/PHE113] Too many conformers generated (17100). Splitting QP scoring.`

Do you know a branch and hash commit I can use to effectively generate appropriate alternate conformers using the files in the `example/` directory?

Thanks!

Additional information regarding the packages:

1. python version: 3.10
2. Numpy version: 1.22
3. cvxpy version: 1.5.2
4. Pandas version: 2.2.2
5. pyscipopt version: 5.1.1
6. Scipy version: 1.14.0
