### ISSUE TITLE
post_refine_phenix.sh script

### ISSUE THREAD

**Issue by reneeotten** [ExcitedStates/qfit-3.0#60]
To me it seems that the line below in the `post_refine_phenix.sh` script is incorrect (at least I get error messages about duplicate atoms).

https://github.com/ExcitedStates/qfit-3.0/blob/5ffdb04e37083f8a9639ff731527ca70576f3d70/scripts/post_refine_phenix.sh#L43

This likely should be `multiconformer_model2.pdb.fixed` to use the file after the duplicates have been removed by the `remove_duplicates` script (or perhaps even `multiconformer_model2.pdb.fixed_modified.pdb` after removing the protons). If that's indeed the case the downstream script will of course need some adjustments to account for that as well.

Additionally, extracting the resolution does not work for me, which might depend on what shell one uses:
https://github.com/ExcitedStates/qfit-3.0/blob/5ffdb04e37083f8a9639ff731527ca70576f3d70/scripts/post_refine_phenix.sh#L21

I think the following will work more robustly: ``` res=`echo ${resrange} | awk '{print $NF}'` ```

I am happy to submit a PR if you prefer, but first just wanted to make sure I am actually right about it ;) Thanks!

**Comment by stephaniewanko** [comment]
Hi Renee,
Sorry for all the back & forth. And thanks for the second set of eyes. As you can see, phenix changes often. I would play around with the script and use it as it works for your specific case. Hopefully, the new pull will fix most of your issues :). I would say this script works for about 80% of PDBs.

**Comment by blake-riley** [comment]
Hi Renee, I've just now merged a bunch of changes to the dev branch related to this.
They should make it through to master within a month.

You may notice that the arguments to the script have changed. Run the command without arguments to see the usage.
The script should (and now does) take into account different filenames that the user might want to use.

Re your comment on `ready_set`, this now uses the f_modified.pdb as you suggested.
Re your comment on the resrange, I went for a double cut, though your awk suggestion would also have worked.
The qfit devs should try to keep this script up to date with phenix output.

I have run the script all the way through now with "not my PDB", so I'm closing this issue now.

Feel free to reopen this issue if you run into a similar issue. (And PRs are always welcome!)

Kind regards,
Blake.
