### ISSUE TITLE
free() error while "converting conformers to density"

### ISSUE THREAD

**Issue by blake-riley** [ExcitedStates/qfit-3.0#66]
I've had two of these errors so far while running qFit:
`free(): invalid next size (normal)`
This might be? is probably? a bug in the C extension?

This occurs in after a `logger.debug("Density")` call, but before a `logger.info("Solving QP")` call.
This narrows it down to something in the `qfit.py::_BaseQFit.convert()` routine, probably in `transformer.py::Transformer.density()`... I'm eyeing the call to `dilate_points()`.

Strangely, the rest of the Python code seems to continue through QP, MIQP, passes a `logger.debug("Remaining valid conformations")` call, but then it dies somewhere in `qfit.py::QFitRotamericResidue.run()`. Not sure exactly where, but it's either `_write_intermediate_conformers` or something in the Validator chokes.

I'm not sure what the pattern is for this bug, or whether there's commonality between this and #65 . I'll try to share a MWE once I do a little more digging.

**Comment by stephaniewankowicz** [comment]
I have not been able to reproduce this bug.
