### ISSUE TITLE
Default values for boolean flags in --help is confusing (please remove double negatives)

### ISSUE THREAD

**Issue by blake-riley** [ExcitedStates/qfit-3.0#69]
**Summary**
On `qfit_protein --help`, argparse will print the usage for available flags.
These flags all display their default values (my commit 7838eb1 is responsible for this).

When the flag is written as a "negative flag" (e.g. --no-sample-angle), the default value printed is a confusing reflection of what the program is doing.

**Current function**
For example:
```
  -sa, --no-sample-angle
                        Do not sample CA-CB-CG angle. (default: True)
```

Here, the `--no-sample-angle` flag is defined as
```python
    p.add_argument('-sa', "--no-sample-angle", action="store_false", dest="sample_angle",
                   help="Do not sample CA-CB-CG angle.")
```

When the flag is set, store_false will set the sample_angle variable to False.
When the flag is not set (i.e. at default), the sample_angle variable will contain True. This is what is shown by the printed default.

**Why this is confusing**
When the user reads this, they will be confused.
A logical thought: "By default, --no-sample-angle is true? So we're not sampling the CA-CB-CG angle?"
This is not correct, since it is the default of the dest variable which is shown (sample_angle is what is True): so we _are_ sampling the CA-CB-CG angle.

**Required change**
Internally, it is a good thing that most "dest" variables are positives (e.g. sample_angle)---this gives clarity when programming.
We should therefore afford the user similar clarity, by rewording all arguments to be positive arguments.
1. The user should be presented a flag with an optional "--no" at the front (e.g. `--[no-]sample-angle`).
2. All "store_false" actions should be eliminated.
3. A lot of single-dash flags will need to be rethought.

A solution would implement a custom ArgParse.Action like [here](https://thisdataguy.com/2017/07/03/no-options-with-argparse-and-python/), or something from [this SO question](https://stackoverflow.com/questions/9234258/in-python-argparse-is-it-possible-to-have-paired-no-something-something-arg) ... [this answer](https://stackoverflow.com/a/36803315) is pretty fantastic.

**Comment by stephaniewankowicz** [comment]
This is completed.
