### ISSUE TITLE
Investigate use of copy.deepcopy in _randomize_bs

### ISSUE THREAD

**Issue by blake-riley** [ExcitedStates/qfit-3.0#80]
https://github.com/ExcitedStates/qfit-3.0/blob/5d9af992ef5c4276facbf5643848548154835823/src/qfit/qfit.py#L267-L273

Here, we're deepcopying the _bs array.
If randomize_b is not set, then do we really need to copy it?

This was one of the slowest remaining parts in profiling. Can we tweak it to make it faster?

**Comment by stephaniewankowicz** [comment]
randomize bs no longer exists.
